config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: :registrations }
  resources :home do
    collection do
      get :about
      get :services
      get :contact
      get :districts
      get :cities
      get :donars
      get :blogpost
      get :bloghome1
      get :bloghome2
      get :faq
      get :portfolio
      get :portfolio1
      get :portfolio2
      get :portfolio3
      get :portfolio4
      get :pricing
      get :sidebar
    end
  end
  resources :users do
    collection do
      get :district
      get :city
      get :dashboard
    end
  end
  resources :cities
  resources :districts
  resources :states
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :state
  belongs_to :district
  belongs_to :city

  def full_name
    first_name + ' ' + last_name
  end

  def self.search(donar)
    select(:first_name, :last_name).where(blood_group: \
        donar[:blood_group], state_id: \
        donar[:state_id], district_id: \
        donar[:district_id], city_id: donar[:city_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:district, :city]

  def district
    @districts ||= State.where(id: params[:id]).take.districts
  end

  def city
    @cities ||= District.where(id: params[:id]).take.cities
  end

  def index
    redirect_to dashboard_users_path if current_user.id != 1
  end

  def dashboard
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_city.html.erb
<div class="field">
    <%= label_tag :city %><br />
    <%= select :user, :city_id, cities, prompt: 'Select city'%>
</div>

app/views/users/_district.html.erb
<div class="field">
	<%= label_tag :district %><br />
	<%= select :user, :district_id, districts, {prompt: 'Select district'}, {onchange: "cities();"}%>
</div>

app/views/users/city.js.erb
$('#city').html("<%= j render 'city' %>")

app/views/users/dashboard.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.full_name %>
</p>
<p>
  <strong>Blood Group:</strong>
  <%= @user.blood_group %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>
<p>
  <strong>State:</strong>
  <%= @user.state.name %>
</p>
<p>
  <strong>District:</strong>
  <%= @user.district.name %>
</p>
<p>
  <strong>City:</strong>
  <%= @user.city.name %>
</p>
<p>
  <strong>Mobile No:</strong>
  <%= @user.mobile1 %>
</p>
<p>
  <strong>Other Mobile No:</strong>
  <%= @user.mobile2 %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email%>
</p>

app/views/users/district.js.erb
$('#district').html("<%= j render 'district' %>")

app/views/users/index.html.erb
<p><%= link_to 'States Details', states_path%></p>
<p><%= link_to 'District Details', districts_path%></p>
<p><%= link_to 'City Details', cities_path%></p>