config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: :registrations }
  resources :home do
    collection do
      get :about
      get :services
      get :contact
      get :districts
      get :cities
      get :donars
      get :blogpost
      get :bloghome1
      get :bloghome2
      get :faq
      get :portfolio
      get :portfolio1
      get :portfolio2
      get :portfolio3
      get :portfolio4
      get :pricing
      get :sidebar
    end
  end
  resources :users do
    collection do
      get :district
      get :city
      get :dashboard
    end
  end
  resources :cities
  resources :districts
  resources :states
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :state
  has_many :cities
  scope :shodh, ->(id) { where(id: id).take }

  def state_name
    state.name if state
  end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_district, only: [:show, :edit, :update, :destroy]

  def index
    @districts ||= District.all
    authorize! :read, @districts
  end

  def new
    @district = District.new
    @states ||= State.all
    authorize! :create, @district
  end

  def create
    @district = District.new(district_params)
    @district.save
    redirect_to districts_path
  end

  def edit
    @states ||= State.all
    authorize! :update, @district
  end

  def update
    @district.update(district_params)
    redirect_to districts_path
  end

  def destroy
    authorize! :delete, @district
    @district.destroy
    redirect_to districts_path
  end

  private

  def set_district
    @district = District.shodh(params[:id])
  end

  def district_params
    params.require(:district).permit(:name, :state_id)
  end
end

app/helpers/districts_helper.rb
module DistrictsHelper
  def districts_errors_messages!
    return if @district.errors.empty?
    msg = @district.errors.full_messages.map { |m| content_tag(:li, m) }.join

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <ul align="left">#{msg}</ul>
    </div>
    HTML
    html.html_safe
  end

  def states
    return if @states.nil?
    @states.collect { |c| [c.name, c.id] }
  end
end

app/views/districts/_form.html.erb
<%= form_for(@district) do |f| %>
  <%= districts_errors_messages! %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.select :state_id, states, prompt: 'Select state' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>Editing district</h1>

<%= render 'form' %>

<%= link_to 'Show', @district %> |
<%= link_to 'Back', districts_path %>

app/views/districts/index.html.erb
<h1>Listing districts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @districts.each do |district| %>
      <tr>
        <td><%= district.name %></td>
        <td><%= district.state_name %></td>
        <td><%= link_to 'Show', district %></td>
        <td><%= link_to 'Edit', edit_district_path(district) %></td>
        <td><%= link_to 'Destroy', district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District', new_district_path %>

app/views/districts/new.html.erb
<h1>New district</h1>

<%= render 'form' %>

<%= link_to 'Back', districts_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @district.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @district.state %>
</p>

<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>